# Generated by Django 5.1.7 on 2026-03-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='model_3d',
            field=models.FileField(blank=True, help_text='GLB/GLTF 3D model', null=True, upload_to='apartment_3d/'),
        ),
    ]
