# Generated by Django 5.1.7 on 2026-03-01 19:53

import all.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0003_object_model_3d_room_type_model_apartment_segment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tashkilot hisoboti',
                'verbose_name_plural': 'Tashkilot hisobotlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='apartment',
            name='model_3d',
            field=models.FileField(blank=True, help_text='.glb/.gltf yoki .zip (ixtiyoriy override)', null=True, upload_to=all.models.Apartment._apartment_3d_upload_to),
        ),
        migrations.AlterField(
            model_name='object',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Asosiy obyekt 3D modeli — .glb/.gltf yoki .zip (ichida model + teksturalar)', null=True, upload_to=all.models.Object._object_3d_upload_to),
        ),
        migrations.AlterField(
            model_name='roomtypemodel',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to=all.models.RoomTypeModel._room_type_3d_upload_to),
        ),
    ]
