# Generated by Django 5.1.7 on 2026-03-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0004_add_organization_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/'),
        ),
    ]
